services:
  app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    user: 1000:1000
    ports:
      - 5173:5173
    command: uvicorn main:api.service --host 0.0.0.0 --port 4000 --reload
